spring: 
  application:  
    name: document-service
  main: 
    allow-bean-definition-overriding: true
  datasource: 
    jdbc-url: jdbc:mysql://10.15.43.30:3306/vtigercrm54
    username: sroot
    password: 12345
    driver-class-name:  com.mysql.cj.jdbc.Driver
  # datasource: 
  #   jdbc-url: jdbc:mysql://localhost:3306/bankmega
  #   username: root
  #   password: Xsis123
  #   driver-class-name:  com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8012
  
logging:
  level: 
    root: warn 
    com:  
      bankmega: debug
      org.springframework.security: debug


springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /

