spring: 
  application:  
    name: document-service
  main: 
    allow-bean-definition-overriding: true
  datasource: 
      jdbc-url: jdbc:mysql://10.15.43.30:3306/vtigercrm54
      username: sroot
      password: 12345
      driver-class-name:  com.mysql.cj.jdbc.Driver
  servlet:  
    multipart:  
      # defining size -1 means its unlimited
      max-file-size:  -1
      max-request-size: -1
 
server:
  port: 8012
  
logging:
  level: 
    root: warn 
    com:  
      bankmega: debug
#      org.springframework.security: debug


springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /
   
directory:  
#  path-name:  C://Users/23020229/Desktop/
  path-name:  /data/document-service/
app: 
  filter: 
    file-type: .tif,.odt,.zip,.wps,.txt,.jpg,.jpeg,.png,.pdf,.rar,.doc,.docx,.xls,.xlsx
    max-size: 3
